language: bash

services:
    - docker

jobs:
    include:
        - stage: 'Tests'
          name: 'Unit Tests'
          script: ./travis-ci.sh test
        - script: ./travis-ci.sh analyse
          name: 'Analyse'
        - stage: Build
          script: ./travis-ci.sh build
          if: branch != main
        - stage: Build & Deploy
          script: ./travis-ci.sh build
          if: branch = main
          deploy:
              provider: pages
              skip_cleanup: true
              github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
              keep_history: true
              local_dir: build/
              on:
                  branch: main
